// Criar um novo leilão
##
# POST http://localhost:8080/auction  HTTP/1.1
# Content-Type: application/json

# {
#     "product_name": "Product 1",
#     "category": "Category 1",
#     "description": "Auction to product 1",
#     "condition": 0
# }

# Listar todos os leilões
# GET http://localhost:8080/auction?status=0  HTTP/1.1
# Content-Type: application/json

// Listar um leilão pelo ID
# GET http://localhost:8080/auction/f8745188-c2dc-4372-8673-e2cef21bd0f0  HTTP/1.1
# Content-Type: application/json

// listar o vencedor de um leilão via id
# GET http://localhost:8080/auction/winner/f8745188-c2dc-4372-8673-e2cef21bd0f0  HTTP/1.1
# Content-Type: application/json

// Dar um lance
##
# POST http://localhost:8080/bid  HTTP/1.1
# Content-Type: application/json

# {
#     "user_id": "ca0a0dd3-8049-41af-aa7d-de116e072ea4",
#     "auction_id": "f8745188-c2dc-4372-8673-e2cef21bd0f0",
#     "amount": 1
# }

// Listar o lance de um leilão pelo ID (VER ???)
# GET http://localhost:8080/bid/f8745188-c2dc-4372-8673-e2cef21bd0f0  HTTP/1.1
# Content-Type: application/json

// Listar um usuário pelo ID
GET http://localhost:8080/user/ca0a0dd3-8049-41af-aa7d-de116e072ea4  HTTP/1.1
Content-Type: application/json