version: '3.8'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/app/auction"
    networks:
      localNetwork:
        ipv4_address: 172.31.0.10

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      localNetwork:
        ipv4_address: 172.31.0.11

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
